matchBlocks=smooth_basalt mud tuff dirt dripstone_block calcite clay granite andesite diorite stone infested_stone copper_ore redstone_ore gold_ore lapis_ore emerald_ore diamond_ore iron_ore coal_ore coarse_dirt deepslate infested_deepslate deepslate_copper_ore deepslate_redstone_ore deepslate_gold_ore deepslate_lapis_ore deepslate_emerald_ore deepslate_diamond_ore deepslate_iron_ore deepslate_coal_ore
connectBlocks=packed_mud
method=overlay
tiles=0-16
faces=all