matchBlocks=stone andesite granite tuff basalt infested_stone copper_ore redstone_ore gold_ore lapis_ore emerald_ore diamond_ore iron_ore coal_ore calcite dripstone_block
method=overlay
tiles=100-116
connectBlocks=diorite
connect=block
faces=top bottom