matchBlocks=stone tuff basalt infested_stone copper_ore redstone_ore gold_ore lapis_ore emerald_ore diamond_ore iron_ore coal_ore
method=overlay
tiles=0-16
connectBlocks=calcite
connect=block
faces=all