matchBlocks=calcite rooted_dirt dripstone_block red_sandstone stone_bricks mossy_stone_bricks cobblestone mossy_cobblestone bricks sandstone clay granite andesite diorite stone dirt coarse_dirt gravel sand red_sand 
connectBlocks=moss_block
method=overlay
tiles=0-16
faces=all
