matchBlocks=moss_block calcite dripstone_block red_sandstone stone_bricks mossy_stone_bricks cobblestone mossy_cobblestone bricks sandstone clay granite andesite diorite stone dirt podzol coarse_dirt gravel sand red_sand 
connectBlocks=pale_moss_block
method=overlay
tiles=0-16
faces=all
