matchBlocks=smooth_basalt packed_mud dirt_path moss_block rooted_dirt pale_moss_block budding_amethyst amethyst_block calcite red_sandstone stone_bricks mossy_stone_bricks cobblestone mossy_cobblestone bricks sandstone clay granite andesite diorite stone infested_stone copper_ore redstone_ore gold_ore lapis_ore emerald_ore diamond_ore iron_ore coal_ore coarse_dirt gravel deepslate infested_deepslate deepslate_copper_ore deepslate_redstone_ore deepslate_gold_ore deepslate_lapis_ore deepslate_emerald_ore deepslate_diamond_ore deepslate_iron_ore deepslate_coal_ore dirt podzol coarse_dirt gravel sand red_sand mud byg:podzol_dacite byg:rocky_stone byg:dacite
connectBlocks=grass_block
tintIndex=0
tintBlock=grass_block
method=overlay
tiles=0-16
faces=top
