matchTiles=textures/block/nature/grass/gt_1.png textures/block/nature/grass/gt_2.png textures/block/nature/grass/gt_3.png textures/block/nature/grass/gt_4.png textures/block/nature/grass/gt_5.png textures/block/nature/grass/gt_6.png textures/block/nature/grass/gt_7.png textures/block/nature/grass/gt_8.png
method=repeat
tiles=1-256
width=16
height=16
