#This file stores configuration options for Iris, such as the currently active shaderpack
#Fri Jun 26 13:47:08 PDT 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=32
shaderPack=Project-Zero-v1.0.zip
