###############################################################################
# Text colors
###############################################################################
# color of exp level text
text.xpbar=c21adb
# color of "Boss Health" text
text.boss=ff00ff
# color of sign text
text.sign=000000